language: python
python:
- '3.8'
- '3.7'
- '3.6'
os: linux
dist: bionic
cache: pip

before_install:
  - sudo apt-get install -y gfortran
  - pip uninstall -y numpy
install: pip install -r requirements.txt coverage coveralls
script: coverage run --include=tom_antares/antares.py tom_antares/tests/run_tests.py
after_success: coveralls

env:
  global:
  - secure: Pws+VdrWRXRzwNXff3xO7MEctkY5b57TrYlQiRsFJRTJSSYi4OFGCGUrNgSPa0MG8yYpjOLQ8PqTLEdtQ9r8uxnfdDnrS+AYrgZqqFDCPUOMmUa6M1EuiiDQWRcmC/AUkyq2qpvyXUhu56caaG8kraehYm4zd+YpXT8YDoBOcR/JsUx124QGyQSJl2c7hQaxLeAQy+q0YFEA1nq8Ou27HFyxknEHDoN6iDJDw3EX8KszHo8G5uKlfYFcVFPlWBwsifukdKKvPi8mEg2jvKin+poRyYWpnL8NxfzdS2/Cz41FCLYGT+17gT2BnEgjYFly2thQiw8hnpXegnk5wA7+JiZTumWRGhVjLfXP5tiV80NVLc4xOJoCDCJKcFxz4d91XsRT4DxHJ3ChT59P5fR1RMQ7nHLhrFS5jyoaiPQTiX5owkGKNPzaQwZ3oXv451Xlvx/RNIpOYDmspuoY7LguKDqjyc8BUE2LgJdeN/ZMP2IJBhVvwK8JrdqhMedvW3FwN+BpJZUsuy4S192JjX6Atqb/L0kIERK98vaF/Cr8dzzFhIoqCStyaasqzC0NSg+dweq2D+4v3RyLWMfU9qS+v2EB94hHxZyIaBW5H84qM4CqlIpCyV6D+YwfOmm0KV0MW+yq5ItIrR/XCfNPJ+d8gtCRJ0Ha18uOfbxb/q9iFZc=
  - secure: BTvdfQMHO0bEK4wIyWhPYQE4EVOq6IgusayQzHQk4pzu2oItRwiQwGhT4Jzb/tzXFaS24Ar1C8nUTvkx2yFkG2CGX44Pn2Lebz4HUagMikX1bluMVMaMndv3WFCNbanYf5cU/9oOEwsIIwu6TSkRaZGWxzrtR+3cLI46+3xTV2EVtCaJY/yahQ8VuvEfqh4/tw45WkTSU/Iin9rsX/23eqHJ8AwLIXyFGHzHtJtGaaSS6Yop/oivkFOjTrRY8uB8LQKS9svpZ6xAvgjw/54sfbmovO46dvgi5A7eyS5iYO0DeVUFVhsrobTxHSJFmMojNrTm3HfTEnw9vTjFDq9V20jGRJVYPUipUfqlAR+juFS95qQZnKWa78QU62QHgHN8GwnWIHQnvGzx1OsF26rSSPwi6SvRSSdIOxTxLN2DvwDd1XlH2KFaZu9FWCDAf+W8IUcvbfVjwYXrrtSfEoxyNLe/jBB+AClVzeKgH+/8y0Z7FOwEKrSygpJ5liyq1OjZf/Gplg5Ho2LU7H2C9pTr6QgbYhvjJQ/NHcBnfa2YWU79ZPBTigDvG8qvz1iY30tDpDo8w0EaO5phCN8kW1wgRExg76h7YEBSQtOovHmY7SjkUbrk3/kRy26ezVEKymQVW/F0I2aqcdIputSaNqvSINMMFYixtYUDJtU150zqO+A=

stages:
- "Style Checks"
- "test"
- "Canary Tests"

jobs:
  include:
  - stage: "Style Checks"
    if: type != cron
    install: pip install -I flake8
    script: flake8 tom_* --max-line-length=120
  - stage: "Canary Tests"
    python: '3.8'
    if: type = cron
    script: python tom_antares/tests/run_canary_tests.py
    
