language: python
python:
- '3.8'
- '3.7'
- '3.6'
os: linux
dist: bionic
cache: pip

before_install:
  - sudo apt-get install -y gfortran
  - pip uninstall -y numpy
install: pip install -r requirements.txt coverage coveralls
script: coverage run --include=tom_antares/antares.py tom_antares/tests/run_tests.py
after_success: coveralls

env:
  global:
  - secure: Pws+VdrWRXRzwNXff3xO7MEctkY5b57TrYlQiRsFJRTJSSYi4OFGCGUrNgSPa0MG8yYpjOLQ8PqTLEdtQ9r8uxnfdDnrS+AYrgZqqFDCPUOMmUa6M1EuiiDQWRcmC/AUkyq2qpvyXUhu56caaG8kraehYm4zd+YpXT8YDoBOcR/JsUx124QGyQSJl2c7hQaxLeAQy+q0YFEA1nq8Ou27HFyxknEHDoN6iDJDw3EX8KszHo8G5uKlfYFcVFPlWBwsifukdKKvPi8mEg2jvKin+poRyYWpnL8NxfzdS2/Cz41FCLYGT+17gT2BnEgjYFly2thQiw8hnpXegnk5wA7+JiZTumWRGhVjLfXP5tiV80NVLc4xOJoCDCJKcFxz4d91XsRT4DxHJ3ChT59P5fR1RMQ7nHLhrFS5jyoaiPQTiX5owkGKNPzaQwZ3oXv451Xlvx/RNIpOYDmspuoY7LguKDqjyc8BUE2LgJdeN/ZMP2IJBhVvwK8JrdqhMedvW3FwN+BpJZUsuy4S192JjX6Atqb/L0kIERK98vaF/Cr8dzzFhIoqCStyaasqzC0NSg+dweq2D+4v3RyLWMfU9qS+v2EB94hHxZyIaBW5H84qM4CqlIpCyV6D+YwfOmm0KV0MW+yq5ItIrR/XCfNPJ+d8gtCRJ0Ha18uOfbxb/q9iFZc=
  - secure: BTvdfQMHO0bEK4wIyWhPYQE4EVOq6IgusayQzHQk4pzu2oItRwiQwGhT4Jzb/tzXFaS24Ar1C8nUTvkx2yFkG2CGX44Pn2Lebz4HUagMikX1bluMVMaMndv3WFCNbanYf5cU/9oOEwsIIwu6TSkRaZGWxzrtR+3cLI46+3xTV2EVtCaJY/yahQ8VuvEfqh4/tw45WkTSU/Iin9rsX/23eqHJ8AwLIXyFGHzHtJtGaaSS6Yop/oivkFOjTrRY8uB8LQKS9svpZ6xAvgjw/54sfbmovO46dvgi5A7eyS5iYO0DeVUFVhsrobTxHSJFmMojNrTm3HfTEnw9vTjFDq9V20jGRJVYPUipUfqlAR+juFS95qQZnKWa78QU62QHgHN8GwnWIHQnvGzx1OsF26rSSPwi6SvRSSdIOxTxLN2DvwDd1XlH2KFaZu9FWCDAf+W8IUcvbfVjwYXrrtSfEoxyNLe/jBB+AClVzeKgH+/8y0Z7FOwEKrSygpJ5liyq1OjZf/Gplg5Ho2LU7H2C9pTr6QgbYhvjJQ/NHcBnfa2YWU79ZPBTigDvG8qvz1iY30tDpDo8w0EaO5phCN8kW1wgRExg76h7YEBSQtOovHmY7SjkUbrk3/kRy26ezVEKymQVW/F0I2aqcdIputSaNqvSINMMFYixtYUDJtU150zqO+A=

stages:
- "Style Checks"
- "test"
- "Canary Tests"
- "Deploy Dev"
- Deploy Main

jobs:
  include:
  - stage: "Style Checks"
    if: type != cron
    install: pip install -I flake8
    script: flake8 tom_* --max-line-length=120
  - stage: "Canary Tests"
    python: '3.8'
    if: type = cron
    script: python tom_antares/tests/run_canary_tests.py
    
  - stage: "Deploy Dev"
    if:
    - tag IS present
    - type != cron
    script: skip
    deploy:
      provider: pypi
      skip_existing: true
      cleanup: false
      on:
        branch: dev
        tags: true
        condition: $TRAVIS_TAG =~ ^[0-9]+\.[0-9]+\.[0-9]+\-(alpha)\.[0-9]+$
      username: "__token__"
      password:
         secure: "rm49DiKk9F0bsTFeoE9S5ROPDWYPkl3LMprGdZhP8n8uEKtBEqYj8mdiM34pQ8MirzMgoPp1lsjpfUJspQlpMnRjqmlnh9PSMev05wMMFo7ivo0s4MJjLj4+LVE8x1fpnT2q6PZ0vbkTn7fpQ+gmGhfQDgoTJI1rNa78hAaE5jGtRhzFttLqV5AUyXFZbMftcKkUTtZQG54wZqdrUz5i2nwD7s5CxWH4K8qSj2y+Z1epxNKtOASaOFMyqpWgmpBkVKMhbvHCfVfdhbGyh/V4JMxP/imLXAUaLR+1BzkfvwSnXGnLNWLTZssRxwPn4vjeHrn3vLBomR8TnXNlLxdd0lDkZXQTdXacu92w1Du0fD+fC8jn1uCqtFXX/ry4nGWCIbJK1pje+tkwSWJVwDF8q9GzDtnMtbaLlScDQ5qI+PhUcnPrXK4UXnK/W55Dkud9unrz/pyt2q/G2+UVX/EfezhMbSAi6CF9Fqv8XaLvyd5JSfWW86RSrJ+akSY+QHHnpV3qu2mDUmFdfjpdOHniURufosyc0qN03+R+AJpMWKVxs8W/QVtW6GpH3c1X+xLlbgAOSUPXsZ4k4tATYaiv7KBRa8IwE/tjlWv8j5nl/ztIXK/1Rtq3EfLQlXZUwm1YaMv2jAxUPj5E/sEy8x0bweLGTSlquqT2HDqp7meHtnA="
      distributions: "sdist bdist_wheel"

  - stage: "Deploy Dev"
    if:
    - tag IS present
    - type != cron
    python: 3.8
    script: skip
    deploy:
      provider: releases
      token:
        secure: "Lf4iHhXUba6K+OYRbZj9lIVMP0oGx9+QaZjCfjoOfqOykJ/vhqQIjcrBfKdDPiwKB2MU3j8twBf1zQQKwyiBiubx6O0yMmBmI/nwWIT19MDNwqLhgSBZuFnd2c5m4XjW+qoqdQdMRk9vD+z4mxWdI+tREXux7IUjvD0utECaUxv+Ue+5/W6C/kWcdAjdtdsXgTPudsnGBMMpOd6UdeAfgFbRWtZJMfzdojDiXKPaMI3RtAe6pNbwaNe7WuqEH93/SCj3ja9gvGtoxGpHoO1XlC0iqs+a8N1jvc9/THTFp8C788+KyvVtaurzFioxSm2C8SuJuV9tjMpKwQUz9YxGzm/iomrL4GlKOi8UKT7EFbsLXPhhO/PQ3yAZmy4Yw/O1Zv1+pOYahLQs2RATCBQukJ5tfphj37S5INhgXIpy/jHiONQnyRmlLIO+7JpBjv6xMyE72pM40WgUaIKxG6OQBjmBxvmkMSlp3G9+WhS4oDzTehw12AS5I63gT+6raHewVivk/QG+5Mj44z3y28O673QaWsYoOrPjff7qzbVLILKE7l4RifycbERYAbjjRsC9KEdFFYViX4c4hD72h9QlVp5U9mPoK9Yw5C9u6Ok+zjVQHVJEkI6LeWs5BlArwWczG5w38bC1GErrLqQinbJGVK4nL9ClCCSAtIyIqk4vcgc="
      on:
        branch: dev
        tags: true
      file_glob: true
      file: dist/*
      cleanup: false
      draft: true
      prerelease: true

  - stage: Deploy Main
    if:
    - tag IS present
    - type != cron
    python: 3.8
    script: skip
    deploy:
      provider: pypi
      skip_existing: true
      cleanup: false
      on:
        branch: main
        tags: true
        condition: $TRAVIS_TAG =~ ^[0-9]+\.[0-9]+\.[0-9]+$
      username: "__token__"
      password:
        secure: "rm49DiKk9F0bsTFeoE9S5ROPDWYPkl3LMprGdZhP8n8uEKtBEqYj8mdiM34pQ8MirzMgoPp1lsjpfUJspQlpMnRjqmlnh9PSMev05wMMFo7ivo0s4MJjLj4+LVE8x1fpnT2q6PZ0vbkTn7fpQ+gmGhfQDgoTJI1rNa78hAaE5jGtRhzFttLqV5AUyXFZbMftcKkUTtZQG54wZqdrUz5i2nwD7s5CxWH4K8qSj2y+Z1epxNKtOASaOFMyqpWgmpBkVKMhbvHCfVfdhbGyh/V4JMxP/imLXAUaLR+1BzkfvwSnXGnLNWLTZssRxwPn4vjeHrn3vLBomR8TnXNlLxdd0lDkZXQTdXacu92w1Du0fD+fC8jn1uCqtFXX/ry4nGWCIbJK1pje+tkwSWJVwDF8q9GzDtnMtbaLlScDQ5qI+PhUcnPrXK4UXnK/W55Dkud9unrz/pyt2q/G2+UVX/EfezhMbSAi6CF9Fqv8XaLvyd5JSfWW86RSrJ+akSY+QHHnpV3qu2mDUmFdfjpdOHniURufosyc0qN03+R+AJpMWKVxs8W/QVtW6GpH3c1X+xLlbgAOSUPXsZ4k4tATYaiv7KBRa8IwE/tjlWv8j5nl/ztIXK/1Rtq3EfLQlXZUwm1YaMv2jAxUPj5E/sEy8x0bweLGTSlquqT2HDqp7meHtnA="
      distributions: "sdist bdist_wheel"

  - stage: Deploy Main
    if:
    - tag IS present
    - type != cron
    python: 3.8
    script: skip
    deploy:
      provider: releases
      token:
        secure: "Lf4iHhXUba6K+OYRbZj9lIVMP0oGx9+QaZjCfjoOfqOykJ/vhqQIjcrBfKdDPiwKB2MU3j8twBf1zQQKwyiBiubx6O0yMmBmI/nwWIT19MDNwqLhgSBZuFnd2c5m4XjW+qoqdQdMRk9vD+z4mxWdI+tREXux7IUjvD0utECaUxv+Ue+5/W6C/kWcdAjdtdsXgTPudsnGBMMpOd6UdeAfgFbRWtZJMfzdojDiXKPaMI3RtAe6pNbwaNe7WuqEH93/SCj3ja9gvGtoxGpHoO1XlC0iqs+a8N1jvc9/THTFp8C788+KyvVtaurzFioxSm2C8SuJuV9tjMpKwQUz9YxGzm/iomrL4GlKOi8UKT7EFbsLXPhhO/PQ3yAZmy4Yw/O1Zv1+pOYahLQs2RATCBQukJ5tfphj37S5INhgXIpy/jHiONQnyRmlLIO+7JpBjv6xMyE72pM40WgUaIKxG6OQBjmBxvmkMSlp3G9+WhS4oDzTehw12AS5I63gT+6raHewVivk/QG+5Mj44z3y28O673QaWsYoOrPjff7qzbVLILKE7l4RifycbERYAbjjRsC9KEdFFYViX4c4hD72h9QlVp5U9mPoK9Yw5C9u6Ok+zjVQHVJEkI6LeWs5BlArwWczG5w38bC1GErrLqQinbJGVK4nL9ClCCSAtIyIqk4vcgc="
      on:
        branch: main
        tags: true
      file_glob: true
      file: dist/*
      cleanup: false
      draft: true
